version: 2.1

orbs:
  docker: circleci/docker@2.0.1

jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: lab1-java-circleci-digitalocean
      DOCKER_TAG: latest
    docker:
      - image: cimg/openjdk:11.0.13
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: run build
          command: |
            chmod +x mvnw
            sed -i "s/\r$//" mvnw
            ./mvnw --version
            ./mvnw package
      - run:
          name: build
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_TAG .
            docker images
            docker push $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_TAG
  deploy:
    executor: docker/docker
    steps:
      - run:
          name: run build
          command: |
            whoami
            pwd
            "echo deploy succes"

workflows:
  my-workflow:
    jobs:
      - build-and-push:
          filters:
            branches:
              only:
                - dev
      - deploy:
          requires:
            - build-and-push
          filters:
            branches:
              only:
                - master
